// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_fit_fun
double rcpp_fit_fun(Rcpp::NumericMatrix ImpCov, Rcpp::NumericMatrix SampCov, int type2, double lambda, arma::vec pen_vec, arma::vec pen_diff);
RcppExport SEXP regsem_rcpp_fit_fun(SEXP ImpCovSEXP, SEXP SampCovSEXP, SEXP type2SEXP, SEXP lambdaSEXP, SEXP pen_vecSEXP, SEXP pen_diffSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type ImpCov(ImpCovSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type SampCov(SampCovSEXP);
    Rcpp::traits::input_parameter< int >::type type2(type2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pen_vec(pen_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pen_diff(pen_diffSEXP);
    __result = Rcpp::wrap(rcpp_fit_fun(ImpCov, SampCov, type2, lambda, pen_vec, pen_diff));
    return __result;
END_RCPP
}
